# Generated by Django 2.2 on 2023-01-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0004_review_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='raiting',
            new_name='rating',
        ),
    ]
